app/blog/routes.py
from flask import Blueprint, request, render_template, flash, redirect, url_for, abort
from flask_login import current_user, login_required

from app.extensions import db, limiter
from app.models import Post, generate_unique_slug
from app.blog.forms import PostForm

bp = Blueprint("blog", __name__)


@bp.route('/blog')
def blog():
    page = request.args.get('page', 1, type=int)

    posts = db.paginate(Post.query.filter(Post.published == True, Post.slug.isnot(None))
        .order_by(Post.timestamp.desc()),
        page=page,
        per_page=5,
        error_out=False
    )

    next_url = url_for('blog.blog', page=posts.next_num) if posts.has_next else None
    prev_url = url_for('blog.blog', page=posts.prev_num) if posts.has_prev else None
    return render_template('blog/index.html', posts=posts.items,
                           next_url=next_url, prev_url=prev_url)

@bp.route('/blog/<slug>')
def post_detail(slug):
    post = (Post.query.filter(Post.slug==slug, Post.published == True).first_or_404())

    return render_template('blog/post.html', post=post)

@bp.route('/blog/new', methods=['GET', 'POST'])
@login_required
@limiter.limit("10 per hour")
def new_blog_post():
    form = PostForm()

    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            summary=form.summary.data,
            body=form.body.data,
            slug=generate_unique_slug(form.title.data),
            author=current_user
        )
        db.session.add(post)
        db.session.commit()
        flash('Your post is live!')
        return redirect(url_for('blog.blog'))

    return render_template('blog/new.html', form=form)

@bp.route('/post/<int:id>/edit', methods=['GET', 'POST'])
@login_required
@limiter.limit("10 per hour")
def edit_post(id):
    post = Post.query.get_or_404(id)
    
    if post.author != current_user:
        abort(403)

    form = PostForm(obj=post)

    if form.validate_on_submit():
        if post.title != form.title.data:
            post.slug = generate_unique_slug(form.title.data)
        
        post.title = form.title.data
        post.summary = form.summary.data
        post.body = form.body.data

        db.session.commit()
        flash('Your post has been updated!')
        return redirect(url_for('blog.post_detail', slug=post.slug))

    return render_template('blog/edit.html', form=form, post=post)

@bp.route('/post/<int:id>/delete', methods=['POST'])
@login_required
@limiter.limit("10 per hour")
def delete_post(id):
    post = Post.query.get_or_404(id)

    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post deleted.')

    return redirect(url_for('main.index'))

app/routes/auth.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user, login_required

from app import db
import sqlalchemy as sa
from app.models import User
from app.forms import LoginForm, ResetPasswordRequestForm, ResetPasswordForm
from app.email import send_password_reset_email
from urllib.parse import urlsplit


bp = Blueprint("auth", __name__)

# @bp.route('/register', methods=['GET', 'POST'])
# def register():
#     if current_user.is_authenticated:
#         return redirect(url_for('index'))
#     form = RegistrationForm()
#     if form.validate_on_submit():
#         user = User(username=form.username.data, email=form.email.data)
#         user.set_password(form.password.data)
#         db.session.add(user)
#         db.session.commit()
#         flash('Congratulations, you are now a registered user!')
#         return redirect(url_for('auth.login'))
#     return render_template('register.html', title='Register', form=form)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == form.username.data))
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('auth.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        #retrieves url the user tried to visit before redirect to login page
        if not next_page or urlsplit(next_page).netloc != '':
            #protects against open redirect attacks
            next_page = url_for('index')
        return redirect(next_page)
    return render_template('login.html', title='Sign In', form=form)

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

@bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('auth.login'))
    return render_template('reset_password.html', form=form)

@bp.route('/reset_password_request', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.email == form.email.data))
        if user:
            send_password_reset_email(user)
        flash('Check your email for the instructions to reset your password')
        return redirect(url_for('auth.login'))
    return render_template('reset_password_request.html',
                           title='Reset Password', form=form)

app/templates/_post.html
<table class="table table-borderless">
    <tr>
        <td width="70px">
            <img src="{{ post.author.avatar(70) }}" class="rounded-circle">
        </td>
        <td>
            <a href="{{ url_for('users.user', username=post.author.username) }}">
                <b>{{ post.author.username }}</b>
            </a>
            <span class="ms-1">{{ moment(post.timestamp).fromNow() }}</span>
            <br>
            {{ post.body_html | safe }}
        </td>
    </tr>
</table>

app/templates/base.html
<!doctype html>
<html lang="en">
    <head> 
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

         {% if title %}
            <title>{{ title }} - AE's Blog</title>
        {% else %}
            <title>Welcome to AE's Blog</title>
        {% endif %}

        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous">
    </head>
      <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">AE's Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
            </li>
            <!--li class="nav-item">
              <a class="nav-link" aria-current="page" href="{{ url_for('main.explore') }}">Explore</a>
            </li>
            <li class="nav-item {% if request.endpoint in ['blog.blog', 'blog.post_detail'] %}active{% endif %}">
              <a class="nav-link" href="{{ url_for('blog.blog') }}">Blog</a>
            </li-->
            <!--- Authenticated user can add blog post -->
            {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('blog.new_blog_post') }}">New Post</a>
              </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav mb-2 mb-lg-0">
            {% if current_user.is_anonymous %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{{ url_for('users.user', username=current_user.username) }}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-3">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
        {% endfor %}
      {% endif %}
      {% endwith %}
      {% block content %}{% endblock %}
    </div>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous">
    </script>
    {{ moment.include_moment() }}
  </body>
</html>

app/templates/bootstrap_wtf.html
{% macro form_field(field, autofocus) %}
  {%- if field.type == 'BooleanField' %}
  <div class="form-check mb-3">
    {{ field(class='form-check-input') }}
    {{ field.label(class='form-check-label') }}
  </div>

  {% elif field.type == 'RadioField' %}
    {{ field.label(class='form-label') }}
    {%- for item in field %}
    <div class="form-check{% if loop.last %} mb-3{% endif %}">
      {{ item(class='form-check-input') }}
      {{ item.label(class='form-check-label') }}
    </div>
    {%- endfor %}
  {%- elif field.type == 'SelectField' %}
    {{ field.label(class='form-label') }}
    {{ field(class='form-select mb-3') }}
  {%- elif field.type == 'TextAreaField' %}
  <div class="mb-3">
    {{ field.label(class='form-label') }}
    {% if autofocus %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
    {% else %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
    {% endif %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
  </div>
  {%- elif field.type == 'SubmitField' %}
  {{ field(class='btn btn-primary mb-3') }}
  {%- else %}
  <div class="mb-3">
    {{ field.label(class='form-label') }}
    {% if autofocus %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
    {% else %}
      {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
    {% endif %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
  </div>
  {%- endif %}
{% endmacro %}

{% macro quick_form(form, action="", method="post", id="", novalidate=False) %}
<form
  {%- if action != None %} action="{{ action }}"{% endif -%}
  {%- if method %} method="{{ method }}"{% endif %}
  {%- if id %} id="{{ id }}"{% endif -%}
  {%- if novalidate %} novalidate{% endif -%}>
  {{ form.hidden_tag() }}
  {%- for field, errors in form.errors.items() %}
    {%- if form[field].widget.input_type == 'hidden' %}
      {%- for error in errors %}
      <div class="invalid-feedback">{{ error }}</div>
      {%- endfor %}
    {%- endif %}
  {%- endfor %}

  {% set ns = namespace(first_field=true) %}
  {%- for field in form %}
    {% if field.widget.input_type != 'hidden' -%}
      {{ form_field(field, ns.first_field) }}
      {% set ns.first_field = false %}
    {%- endif %}
  {%- endfor %}  
</form>
{% endmacro %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  <div class="col-md-3 text-center">
    <img src="{{ url_for('static', filename='headshot.PNG') }}"
         class="rounded-circle mb-3"
         width="128">

    <h3>Arielle Ezechukwu</h3>
    <p class="text-muted">
      Python • Cloud • Security • Working Mom Musings
    </p>
  </div>

  <div class="col-md-9">
    <p>
      I’m a systems thinker, who likes to tinker. Here I write about real-world incidents,
      vulnerabilities, and lessons learned. You'll also find recaps of my projects and career
      insights from my journey in tech.
    </p>

    <hr>

    <h4>Latest Writing</h4>

    {% if latest_posts %}
      {% for post in latest_posts %}
        <article class="mb-3">
          <h5>
            <a href="{{ url_for('blog.post_detail', slug=post.slug) }}">
              {{ post.title }}
            </a>
          </h5>

          {% if post.summary %}
            <p class="text-muted mt-1 mb-1">
              {{ post.summary }}
            </p>
          {% endif %}

          <small class="text-muted">
            {{ moment(post.timestamp).format('LL') }}
          </small>
        </article>
      {% endfor %}
    {% else %}
      <p>No posts yet.</p>
    {% endif %}

    <a href="{{ url_for('blog.blog') }}">View all posts →</a>
  </div>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% import "bootstrap_wtf.html" as wtf %}

{% block content %}
    <h1>Sign In</h1>
    {{ wtf.quick_form(form) }}
    {# Registration disable: single-authour blog #}
    {# <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p> #}
    <p>
        Forgot Your Password?
        <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
    </p>
{% endblock %}